### ISSUE TITLE
[Feature Request] MarkdownTextBlock

### ISSUE THREAD

**Issue by ghost1372** [ModernWpf-Community/ModernWpfCommunityToolkit#6]
Hi Can you port MarkdownTextBlock from WindowsCommunityToolkit to WPF?
https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/markdowntextblock
https://github.com/windows-toolkit/WindowsCommunityToolkit/tree/master/Microsoft.Toolkit.Uwp.UI.Controls.Markdown

**Comment by ShankarBUS** [comment]
It is already here!

Directory in this repo:
https://github.com/ModernWpf-Community/ModernWpfCommunityToolkit/tree/master/ModernWpf.Toolkit.UI.Controls.Markdown

NuGet package:
https://www.nuget.org/packages/ModernWpf.Toolkit.UI.Controls.Markdown/

TBH it was the first control I ported from **WindowsCommunityToolkit** which led me to create this toolkit!

Thanks for asking though 😄.

**Comment by ghost1372** [comment]
@ShankarBUS  thank you❤
one more question😁
Is it possible to load the Md file from path?

**Comment by ShankarBUS** [comment]
You kind of can.

But you need to manually read the file content and load it into the text property.

See this for reference:
https://github.com/ModernWpf-Community/ModernWpfCommunityToolkit/blob/be312f3d3f3dc52bde682e930b9242558121b6c5/ModernWpf.Toolkit.SampleApp/MainWindow.xaml.cs#L93-L106

**Comment by ghost1372** [comment]
@ShankarBUS  thank you for your help
i think there is a bug because # cant be rendered or i miss something?
![Untitled](https://user-images.githubusercontent.com/9213496/99151947-f9fc6000-26b3-11eb-96e0-3592352016a4.png)

**Comment by ShankarBUS** [comment]
`# test` should render

# test

I guess there are some problems with themeing?
It could be white in color. Could you try selecting the text on it?

**Comment by ghost1372** [comment]
> `# test` should render
> 
> # test
> I guess there are some problems with themeing?

yes `Header1Foreground="Red"` fixed 
tnx again

**Comment by ShankarBUS** [comment]
Oh great!

I forgot one thing.
The control doesn't have the necessary theme resources built-in.
Some resources have to be added manually to the App.xaml.

See this for referrence:
https://github.com/ShankarBUS/ModernFlyouts/blob/b852f6cc7a4e6a207012251cec5ff90e82da5d75/ModernFlyouts/App.xaml#L10-L47

**Comment by ghost1372** [comment]
Great now all styles loaded👍👍

**Comment by ShankarBUS** [comment]
You're my first customer 🤣. Even I couldn't use it my own app 😔. Thanks for giving it a try!

**Comment by ShankarBUS** [comment]
@ghost1372,

In case you're still interested in using this toolkit, I want you to know that this toolkit is stable and is ready to be used in other projects.

v0.1 release is out now on Nuget. The setup process is so simple now.

What you need to do in order to use the `MarkdownTextBlock` is
1. Install the [`ModernWpfUI`](https://www.nuget.org/packages/ModernWpfUI/) nuget package and follow the instructions provided with it.
2. Install the [`ModernWpf.Toolkit.UI.Controls.Markdown`](https://www.nuget.org/packages/ModernWpf.Toolkit.UI.Controls.Markdown/) nuget package.
3. Add these to your `App.xaml` https://github.com/ModernWpf-Community/ModernWpfCommunityToolkit/blob/8bbe2231087575df182a7740839b92e917fa711b/ModernWpf.Toolkit.SampleApp/App.xaml#L5 https://github.com/ModernWpf-Community/ModernWpfCommunityToolkit/blob/8bbe2231087575df182a7740839b92e917fa711b/ModernWpf.Toolkit.SampleApp/App.xaml#L10-L16

That's it!

For reference you could check up the [ModernWpf.Toolkit.SampleApp project](https://github.com/ModernWpf-Community/ModernWpfCommunityToolkit/tree/8bbe2231087575df182a7740839b92e917fa711b/ModernWpf.Toolkit.SampleApp).

If you have dropped the idea of using this toolkit, no problems I understand. I just wanted you to know since you seemed to be interested in using this toolkit 😃.

**Comment by ghost1372** [comment]
I'm still interested in this project. Thank you for letting me know.
I recently created an unofficial version of ModernWpf that is not dependent on WinRT
Can I add this control to my unofficial version?

**Comment by ShankarBUS** [comment]
Do whatever you want!

But don't forget to attribute the .NET foundation. Some good MS employee suggested me to do it so that we could avoid any licensing issues. I would recommend you to do so.

**Comment by ghost1372** [comment]
Thank you, I will definitely consider it.❤
